TARGET_INDEX: 9
REF_INDICES_RANGE: [10, 40]
CLASSIFIER_LABEL: "male"
DATASET_SPLIT: "test"
SHAPLEY_1_RUN_ID: "1f4e62b94ab74e18a31fbefdb2e6b7f2"
SHAPLEY_2_RUN_ID: "c6628cf0b68b4c42aac624bdd64efe46"
FEATURES:
  - eyes
  - nose
  - mouth
  - hair
PRED_PROB: false
MLFLOW_EXPERIMENT_NAME: "bilinear"
MLFLOW_RUN_NAME: "target_9_male_4"
