TARGET_INDEX: 5
REF_INDICES_RANGE: [30, 40]
DATASET_SPLIT: "test"
SHAPLEY_1_RUN_ID: "5d266e8e6291456492b7e8a353c92aae"
SHAPLEY_2_RUN_ID: "e7e8b90903084390b0cb714250d0010b"
FEATURES:
  - eyes
  - mouth
TAU: 0.5
NFE: 100
PRED_PROB: false
MLFLOW_EXPERIMENT_NAME: "bilinear"
MLFLOW_RUN_NAME: "target_5_n2_attractive_2"
