DATASET_SPLIT: "test"
MLFLOW_EXPERIMENT_NAME: "fi_blackfill"
TEST_SIZE: 0.5
NUM_EPOCHS: 20
LR: 0.001
BATCH_SIZE: 32
SEED: 42
MODEL_SAVE_PATH: "models/retrained"
TOP_K: 3

TRAINING_EXPERIMENT_NAME: "retrain_blackfill"
TRAINING_RUN_NAME: "blackfill_topk_3"
SHAPLEY_ARTIFACT_SUBDIR: "shapley/values/target_XXXX_1_shapley_values_001.json"