N_SAMPLES: 100
CLASSIFIER_LABEL: "male"
BALANCE_LABEL: "Male"
DATASET_SPLIT: "test"
FEATURES:
  - eyes
  - nose
  - mouth
SUBSTITUTION: "substitution"
COLOR_FILL: [0, 0, 0]
TAU: 0.5
NFE: 20
BATCH_SIZE: 16
CLIP_BATCH_SIZE: 16
INPUT_IMAGE_SIZE: 128
SEED: 42
LOG_IMAGES: 8
MLFLOW_EXPERIMENT_NAME: "roar_eval"
MLFLOW_RUN_NAME: "male_substitution_roar_eval"
