TARGET_INDEX: 2471
# REF_INDICES_RANGE: [10, 40]
N_SAMPLES: 20
N: 1
CLASSIFIER_LABEL: "male"
SUBSTITUTION: "i2sb"
DATASET_SPLIT: "test"
FEATURES: 
  - eyes
  - nose
  - mouth
TAU: 0.5
NFE: 10
PRED_PROB: false
KEEP_INTERMEDIATE_VALUES: false
MLFLOW_EXPERIMENT_NAME: "final_tau_0.5_nfe_10"
MLFLOW_RUN_NAME: "target_2471_male_N1_tau_0.5_nfe_10"
