TARGET_INDEX: 649
# REF_INDICES_RANGE: [10, 40]
N_SAMPLES: 64
N: 1
CLASSIFIER_LABEL: "male"
SUBSTITUTION: "i2sb"
DATASET_SPLIT: "test"
FEATURES: 
  - eyes
  - nose
  - mouth
TAU: 0.5
NFE: 100
PRED_PROB: false
KEEP_INTERMEDIATE_VALUES: true
MLFLOW_EXPERIMENT_NAME: "shapley"
MLFLOW_RUN_NAME: "target_649_male_N1_tau_0.5_nfe_100"
